services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongonet
    command: mongod --replSet rs0 --bind_ip_all
    restart: always

  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongonet
    command: mongod --replSet rs0 --bind_ip_all
    restart: always

  mongo3:
    image: mongo:latest
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongonet
    command: mongod --replSet rs0 --bind_ip_all
    restart: always

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  mongonet:
    driver: bridge
